apiVersion: v1
kind: List
items:
- kind: ProjectRequest
  apiVersion: v1
  metadata:
    name: tasks-build
    creationTimestam: null
  displayName: Tasks - Build
- kind: ProjectRequest
  apiVersion: v1
  metadata:
    name: tasks-dev
    creationTimestam: null
  displayName: Tasks - DEV
- kind: ProjectRequest
  apiVersion: v1
  metadata:
    name: tasks-test
    creationTimestam: null
  displayName: Tasks - TEST
- kind: ProjectRequest
  apiVersion: v1
  metadata:
    name: tasks-prod
    creationTimestam: null
  displayName: Tasks - PROD
