---
- name: Create Openshift Tasks Projects
  hosts: localhost
  connection: local
  tasks:
    - name: Create Tasks-Build Project
      command: "oc new-project tasks-build --display-name='Tasks Build' --description='Tasks Build Project'"
    - name: Remove the Default Network Policies
      command: "oc delete networkpolicy {{ item }} -n tasks-build"
      with_items:
        - allow-from-default-namespace
        - allow-from-same-namespace
        - default-deny-all
    - name: Remove the Default Limit Range
      command: "oc delete limitrange project-limits -n tasks-build"
    
    - name: Create Tasks-DEV Project
      command: "oc new-project tasks-dev --display-name='Tasks DEV' --description='Tasks DEV Project'"
    - name: Remove the Default Network Policies
      command: "oc delete networkpolicy {{ item }} -n tasks-dev"
      with_items:
        - allow-from-default-namespace
        - allow-from-same-namespace
        - default-deny-all
    - name: Remove the Default Limit Range
      command: "oc delete limitrange project-limits -n tasks-dev"
    
    - name: Create Tasks-TEST Project
      command: "oc new-project tasks-test --display-name='Tasks TEST' --description='Tasks TEST Project'"
    - name: Remove the Default Network Policies
      command: "oc delete networkpolicy {{ item }} -n tasks-test"
      with_items:
        - allow-from-default-namespace
        - allow-from-same-namespace
        - default-deny-all
    - name: Remove the Default Limit Range
      command: "oc delete limitrange project-limits -n tasks-test"

    - name: Create Tasks-PROD Project
      command: "oc new-project tasks-prod --display-name='Tasks PROD' --description='Tasks PROD Project'"
    - name: Remove the Default Network Policies
      command: "oc delete networkpolicy {{ item }} -n tasks-prod"
      with_items:
        - allow-from-default-namespace
        - allow-from-same-namespace
        - default-deny-all
    - name: Remove the Default Limit Range
      command: "oc delete limitrange project-limits -n tasks-prod"

- name: Configure Policy on the Tasks Projects
  hosts: localhost
  connection: local
  tasks:
    - name: Add Jenkins Service Account access
      command: "oc policy add-role-to-user edit system:serviceaccount:cicd-dev:jenkins -n {{ item }}"
      with_items:
        - tasks-build
        - tasks-dev
        - tasks-test
        - tasks-prod

- name: Configure Policy on the CICD-DEV Project
  hosts: localhost
  connection: local
  tasks:
    - name: Add Project Service Account Group access
      command: "oc policy add-role-to-group system:image-puller system:serviceaccounts:{{ item }} -n cicd-dev"
      with_items:
        - tasks-build
        - tasks-dev
        - tasks-test
        - tasks-prod        
      