---
- name: Disable User Provisioning
  hosts: localhost
  connection: local
  tasks:
    - name: Remove Self-Provisioners from OAUTH Group
      command: oc adm policy remove-cluster-role-from-group self-provisioner system:authenticated:oauth
      
    #- name: Prevent OpenShift Updates from restoring Self-Provisioners
    #  command: oc patch clusterrolebinding.rbac self-provisioners -p '{ "metadata": { "annotations": { "rbac.authorization.kubernetes.io/autoupdate": "false" } } }'
 