---
# Params:
#        username - user to be added
#        password - password for the user
#
- name: Create a User in htpasswd
  hosts: masters
  vars:
    username:
    password:
  tasks:
    - name: Add User to the htpasswd file
      command: "htpasswd -b /etc/origin/master/htpasswd {{ username }} {{ password }}"