apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: tasks-hpa
spec:
  scaleTargetRef:
    kind: DeploymentConfig
    name: tasks
    apiVersion: apps.openshift.io/v1
    subresource: scale
  minReplicas: 1
  maxReplicas: 5
  cpuUtilization:
    targetCPUUtilizationPercentage: 80

